name: 'Heroku Deploy Python'
author: 'Mehedi Hasan Shojib'
description: 'Deploy your application to Heroku using Python scripts.'
branding:
  icon: 'upload-cloud'
  color: 'green'

inputs:
  heroku_api_key:
    description: >
      Heroku API key used for authentication. 
      Ensure this key has sufficient permissions to deploy your application.
    required: true
  heroku_email:
    description: >
      The email associated with your Heroku account.
    required: true
  heroku_app_name:
    description: >
      The name of your Heroku application.
    required: true
  branch:
    description: >
      The Git branch to deploy. Defaults to "main".
    default: main
    required: false
  usedocker:
    description: >
      Set to "true" to deploy using Docker. Defaults to "false".
    default: false
    required: false
  docker_heroku_process_type:
    description: >
      Specify the process type when using Docker (e.g., "web", "worker").
      Required only if "usedocker" is true.
    required: false
  dontautocreate:
    description: >
      Set to "true" to skip auto-creation of the Heroku app.
    default: false
    required: false
  region:
    description: >
      The Heroku region for app creation (e.g., "us", "eu"). Optional.
    required: false
  team:
    description: >
      The Heroku team for app creation. Optional.
    required: false
  stack:
    description: >
      The Heroku stack to use for app creation (e.g., "container"). Optional.
    required: false
  delay:
    description: >
      Delay in seconds after deployment to ensure changes are applied.
      Defaults to "0" (no delay).
    default: 0
    required: false

outputs:
  deployment_status:
    description: >
      The result of the deployment process (e.g., "success", "failed").
    value: ${{ steps.deploy-app.outputs.deployment_status }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt
    
    - name: Deploy to Heroku
      id: deploy-app
      shell: bash
      run: |
        args=( "--heroku_api_key" "${{ inputs.heroku_api_key }}" )
        args+=( "--heroku_email" "${{ inputs.heroku_email }}" )
        args+=( "--heroku_app_name" "${{ inputs.heroku_app_name }}" )
        args+=( "--branch" "${{ inputs.branch }}" )
        args+=( "--usedocker" "${{ inputs.usedocker }}" )
        if [[ "${{ inputs.docker_heroku_process_type }}" != "" ]]; then
          args+=( "--docker_heroku_process_type" "${{ inputs.docker_heroku_process_type }}" )
        fi
        args+=( "--dontautocreate" "${{ inputs.dontautocreate }}" )
        if [[ "${{ inputs.region }}" != "" ]]; then
          args+=( "--region" "${{ inputs.region }}" )
        fi
        if [[ "${{ inputs.team }}" != "" ]]; then
          args+=( "--team" "${{ inputs.team }}" )
        fi
        if [[ "${{ inputs.stack }}" != "" ]]; then
          args+=( "--stack" "${{ inputs.stack }}" )
        fi
        args+=( "--delay" "${{ inputs.delay }}" )
        
        echo "Running deploy.py with arguments: ${args[@]}"
        python ${{ github.action_path }}/deploy.py "${args[@]}"